import React from 'react';
import './Hero.css';

const Hero = () => {
  return (
    <section className="hero-section" id="home">
      {/* Background Image generated by AI placeholder */}
      <img src="/hero_banner.png" alt="Luxury Ethnic Wear" className="hero-bg" />
      <div className="hero-overlay"></div>
      
      <div className="hero-content fade-in">
        <h1 className="hero-title">Luxury Ethnic Wear, <br/>Designed For Elegance.</h1>
        <p className="hero-subtitle">
          Discover handcrafted Punjabi suits, premium co-ord sets, and timeless boutique collections curated for modern women.
        </p>
        
        <div className="hero-actions">
          <button className="btn-primary">Shop Collection</button>
          <a href="https://wa.me/1234567890" target="_blank" rel="noreferrer" className="btn-whatsapp">
            <i className="fab fa-whatsapp"></i> WhatsApp to Order
          </a>
        </div>
      </div>
    </section>
  );
};

export default Hero;
